name: Angular CI/CD

on:
  push:
    branches: [ "production" ] # Only trigger on pushes to the 'production' branch
  pull_request:
    branches: [ "main" ] # Also trigger on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use Node.js version 18

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint 

      - name: Run unit tests
        run: npm run test